development:
      adapter: mysql
      database: devdev
      port: 3306
     

test: &test
      adapter: mysql
      database: test
      port: 3306
    

production:
      adapter: mysql
      database: prod
      port: 3306

cucumber:
  <<: *test
